### PR TITLE
Feature/omero openbis metadata

### PR DESCRIPTION
**Pull request by wow-such-code**
- search for barcoded sample in order to fetch space and set correct parent sample
- check incoming metadata in order to create respective number of experiments in openbis
- create imaging samples for these experiments
- add metadata to experiments
- provide framework to add metadata for samples, should such metadata be available/part of the data model in the future

### CODE REVIEW

**Comment by wow-such-code** [comment]
This is untested for now. Working on it.

**Comment by wow-such-code** [comment]
[Complete functionality to register metadata in openBIS](https://trello.com/c/uUb90669/548-complete-functionality-to-register-metadata-in-openbis)

**Comment by wow-such-code** [comment]
[Complete functionality to register metadata in openBIS](https://trello.com/c/uUb90669/548-complete-functionality-to-register-metadata-in-openbis)

**Comment by wow-such-code** [comment]
works now, without the omero part

**Comment by luiskuhn** [comment]
Looks good to me

**Review by luiskuhn — APPROVED** [review]
Looks good to me

**Pull request merged**
